tasks:
  - name: prebuild
    init: |
      cd /workspace/.vscode-remote/extensions
      echo "Installing git-log--graph..."
      wget https://open-vsx.org/api/phil294/git-log--graph/0.1.12/file/phil294.git-log--graph-0.1.12.vsix
      chmod 777 phil294.git-log--graph-0.1.12.vsix 
      code --install-extension /workspace/.vscode-remote/extensions/phil294.git-log--graph-0.1.12.vsix
  - name: terraform
    before: |
      source ./bin/install_terraform_cli
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - phil294.git-log--graph-0.1.12
